language: python
python:
  - "3.8"
sudo: required

services:
  - docker

script:
    - echo 'test'

deploy:
    provider: heroku
    api_key: $HEROKU_API_KEY
    app : squaremaster
    skip_cleanup: True